# Generated by Django 3.2.5 on 2021-09-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_login_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='Unnamed User', max_length=30, verbose_name='first name'),
        ),
    ]
